# Generated by Django 3.2.15 on 2022-09-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='front_end',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=120)),
                ('tag_line', models.CharField(max_length=122)),
                ('note', models.CharField(max_length=100)),
            ],
        ),
    ]
