# Generated by Django 3.2.15 on 2022-09-23 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='front_end',
            new_name='home',
        ),
    ]
