# Generated by Django 3.2.15 on 2022-09-24 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontendapp', '0002_rename_front_end_home'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home',
            new_name='front_end',
        ),
    ]
